version: '3'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 8123:8123
    volumes:
      - ./tmp/config:/config
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./tmp/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./tmp/mosquitto/data:/mosquitto/data
      - ./tmp/mosquitto/log:/mosquitto/log